# Generated by Django 3.0.4 on 2020-03-27 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0002_complaint'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items_json', models.CharField(max_length=2000)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('car', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('licenseno', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=500)),
            ],
        ),
    ]
